# Generated by Django 4.0.6 on 2022-08-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('date_created',)},
        ),
    ]
