# Generated by Django 4.0.6 on 2022-08-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_vehicle_options'),
        ('fastcars', '0005_testimonial_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admin_panel.vehicle'),
        ),
    ]
