# Generated by Django 4.0.6 on 2022-08-03 20:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='vehicle_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image2', models.ImageField(upload_to='vehicle_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image3', models.ImageField(upload_to='vehicle_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('vehicle_model', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=5)),
                ('mileage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('chasis_number', models.CharField(max_length=18)),
                ('horsepower', models.IntegerField()),
                ('transmission', models.CharField(choices=[('None', 'None'), ('Manual', 'Manual'), ('Automatic', 'Automatic')], default='None', max_length=10)),
                ('doors', models.IntegerField()),
                ('wheel', models.CharField(choices=[('None', 'None'), ('2', '2'), ('4', '4')], default='None', max_length=10)),
                ('seat', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='admin_panel.brand')),
            ],
        ),
    ]
