# Generated by Django 4.0.6 on 2022-08-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
