# Generated by Django 4.0.6 on 2022-08-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_contact_content_remove_contact_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
