# Generated by Django 4.0.6 on 2022-08-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_logo',
        ),
    ]
